[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "Chi Siamo"
url = "about"
weight = 20
title = "Scopri di più sulla nostra missione"


[[main]]
name = "Intelligenza Artificiale"
url = "services/servizi-intelligenza-artificiale"
weight = 30
title = "Scopri i nostri servizi di intelligenza artificiale"

[[main]]
name = "Cybersecurity"
url = "services/servizi-cybersecurity"
weight = 40
title = "Scopri i nostri servizi di cybersecurity"

[[main]]
name = "Formazione"
url = "formazione-intelligenza-artificiale-e-cybersecurity"
weight = 50
title = "Scopri i nostri corsi di formazione AI e Cybersecurity"
#[[main]]
#identifier = "blog"
#name = "Blog"
#url = "post"
#weight = 60
#title = "Leggi i nostri articoli"
